# Generated by Django 4.0.4 on 2022-06-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='carfueltype',
            options={'verbose_name': 'FuelType', 'verbose_name_plural': 'FuelTypes'},
        ),
        migrations.AlterModelOptions(
            name='cartype',
            options={'verbose_name': 'CarType', 'verbose_name_plural': 'CarTypes'},
        ),
        migrations.AddField(
            model_name='carfueltype',
            name='name',
            field=models.CharField(choices=[('Olej napędowy', 'Olej napędowy'), ('Benzyna', 'Benzyna'), ('Elektryczny', 'Elektryczny')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cartype',
            name='opis',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='carfueltype',
            name='fueltype',
        ),
        migrations.AddField(
            model_name='carfueltype',
            name='fueltype',
            field=models.ManyToManyField(to='CarRental.cartype'),
        ),
        migrations.AlterField(
            model_name='cartype',
            name='type',
            field=models.CharField(choices=[('Klasa A', 'Klasa A'), ('Klasa B', 'Klasa B'), ('Klasa C', 'Klasa C'), ('Klasa D', 'Klasa D'), ('Klasa E', 'Klasa E'), ('Klasa F', 'Klasa F'), ('Klasa S', 'Klasa S'), ('Klasa H', 'Klasa H'), ('Klasa J', 'Klasa J'), ('Klasa M', 'Klasa M')], max_length=50),
        ),
    ]
